language:
  - java
  - node_js
java:
  - "1.8"
jdk:
  - oraclejdk8
node_js:
  - "0.12"
branches:
  only:
    - master
sudo: required
before_install:
  - sudo pip install docker-compose
  - npm install -g npm
  - npm install -g grunt-cli bower
  - bower install
  - npm install
install:
  - mvn clean package -Pprod
after_install:
  - docker build -t nemomen/taa -f Dockerfile .
  - docker login -u nemomen -p 1camel -e stephane.mangin@freesbee.fr
  - docker push nemomen/taa
  - docker-compose up -d
  - docker-compose scale service=3
before_script:
  - grunt build
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

