language:
  - java
  - node_js
java:
  - "1.8"
jdk:
  - oraclejdk8
node_js:
  - "0.12"
branches:
  only:
    - master
sudo: required
before_install:
  - sudo apt-get install -y docker-engine
  - sudo service docker start
  - sudo apt-get install -y docker-compose
  - npm install -g npm
  - npm install -g grunt-cli bower
  - bower install
  - npm install
  - docker-compose up -d
install:
  - mvn clean package
before_script:
  - grunt build
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

