language:
  - java
  - node_js
java:
  - "1.8"
jdk:
  - oraclejdk8
node_js:
  - "0.12"
branches:
  only:
    - master
sudo: required
before_install:
  - sudo apt-get install -y python-pip
  - pip install docker-compose
  - docker-compose stop
  - docker-compose rm -f postgres
  - docker-compose rm -f service
  - docker-compose rm -f interlock
  - npm install -g npm
  - npm install -g grunt-cli bower
  - bower install
  - npm install
install:
  - mvn clean package -p prod
after_install:
  - docker-compose up -d
  - docker-compose scale service=3
before_script:
  - grunt build
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

