language:
  - java
  - node_js
java:
  - "1.8"
jdk:
  - oraclejdk8
node_js:
  - "0.12"
branches:
  only:
    - master
sudo: false
before_install:
  - npm install -g grunt-cli bower
  - bower install
  - npm install
install: mvn clean install
before_script: grunt build
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

