# Interlock/HAProxy
interlock:
    image: ehazlett/interlock:latest
    ports:
        - "80:80"
    volumes:
        - /var/lib/docker:/etc/docker
    command: "--swarm-url tcp://<SWARM_MASTER_IP>:3375 --debug --plugin haproxy start"

postgres:
    image: postgres
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_PASSWORD=123456789abc
        - POSTGRES_USER=TODOApp

service:
    image: taa_tp/todoapp
    volumes:
        - target
    expose:
        - "8080"
    links:
        - postgres
    environment:
    - VIRTUAL_HOST=org.istic.taa.totoapp.service
