# Interlock/HAProxy
interlock:
    image: ehazlett/interlock:latest
    ports:
        - "80:80"
    volumes:
        - /var/lib/docker:/etc/docker
 command: "--swarm-url tcp://<SWARM_MASTER_IP>:3375 --debug --plugin haproxy start"

mysql:
    image: mysql
    container_name: mysql
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=123456789abc

service:
    image: taa_tp/todoapp
    expose:
        - "8080"
    links:
        - mysql
    environment:
    - VIRTUAL_HOST=org.istic.taa.totoapp.service

proxy:
    image: jwilder/nginx-proxy
    ports:
        - "80:80"
    links:
        - service
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
