service_proxy:
    image: jwilder/nginx-proxy
    ports:
    - "80:80"
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro

service_loadbalancing:
    image: hazelcast/hazelcast
    ports:
    - "5701:5701"

database:
    image: mysql:latest
    container_name: database
    ports:
    - "3306:3306"
    environment:
    - ROOT_PWD=56dsf45g9sdf59g19

service_instance_1:
    image: taa_tp/todoapp
    expose:
    - "8080"
    links:
    - database
    environment:
    - VIRTUAL_HOST=org.istic.taa.totoapp.service

service_instance_2:
    image: taa_tp/todoapp
    expose:
    - "8080"
    links:
    - database
    environment:
    - VIRTUAL_HOST=org.istic.taa.totoapp.service

service_instance_3:
    image: taa_tp/todoapp
    expose:
    - "8080"
    links:
    - database
    environment:
    - VIRTUAL_HOST=org.istic.taa.totoapp.service
